server.port=8080
firebase.project.id=${FIREBASE_PROJECT_ID:script-reader-af9b1}
firebase.service.account.path=${FIREBASE_SERVICE_ACCOUNT_PATH:firebase-key.json}

spring.config.import=optional:file:.env[.properties]
spring.config.import=optional:file:.env
